#pragma once

/* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
*/



class Problem2 {
public:


	void solve() {
		long sum = 0;
		for (int i = 1, n = 0; (n = fib(i)) < 4000000; i++) {
			if (n % 2 == 0) {
				sum += n;
			}
		}

		printf("Sum: %d\n", sum);


	}

	// returns the fibonacci sum for the n-th value in the series
	int fib(int n) {
		if (n == 1) return 1;
		if (n == 2) return 2;

		return (fib(n - 1) + fib(n - 2));
	}



};